const constants = {
  LOGIN: 'LOGIN',
  EDIT_TEACHER_ID: 'EDIT_TEACHER_ID',
  EDIT_TEACHER_EMAIL: 'EDIT_TEACHER_EMAIL',
  EDIT_TEACHER_NAME: 'EDIT_TEACHER_NAME',
  DELETE_TEACHER: 'DELETE_TEACHER',
  //ADD_STUDENT: 'ADD_STUDENT',
  LOGIN_STUDENTS: 'LOGIN_STUDENTS',
  EDIT_STUDENT: 'EDIT_STUDENT',
  DELETE_STUDENT: 'DELETE_STUDENT',
  ADD_ASSIGNMENT: 'ADD_ASSIGNMENT',
  EDIT_ASSIGNMENT: 'EDIT_ASSIGNMENT',
  DELETE_ASSIGNMENT: 'DELETE_ASSIGNMENT',
  EMAIL_ASSIGNMENT: 'EMAIL_ASSIGNMENT'
};

export default constants;
